import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Theme} from "@radix-ui/themes";
import NavBar from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="{inter.className}">
        <Theme>
          <header style = {{ backgroundColor: "#f0f0f0", padding: "1rem", textAlign: "center" }}>
          <h1>My App</h1>
          </header>
          <NavBar />
          <main className = 'p-5'>  {children} </main>
        </Theme>
       <footer style ={{backgroundColor: "#f0f0f0", padding: "1rem", textAlign: "center" }}>
          <p>&copy; 2026 My App. All rights reserved.</p>
        </footer>
        </body>
    </html>
  );
}
