import "@radix-ui/themes/styles.css";
import './theme-config.css';
import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono  } from "next/font/google";
import "./globals.css";
import ThemeClient from "./ThemeClient";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { cn } from "@/lib/utils";
import { SeparatorVertical } from "@/components/Separator";

// KEEP THIS ONE: Maps seamlessly to the "font-sans" utility configuration class
const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* REMOVED DUPLICATE: 
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
}); 
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/ethio-telecom-logo.ico", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en" className={cn("font-sans", geist.variable)} >
      <body className={geist.variable}>
        <AuthProvider>
          <QueryClientProvider>
               <Theme accentColor="lime" scaling="105%">
                 <NavBar/>
              <main className = 'p-5'> 
                <Container>
                   {children}
                </Container>
              </main>
            </Theme>
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}